// <auto-generated />
using System;
using EmployeeContacts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeContacts.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315070344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("EmployeeContacts.Infrastructure.Persistence.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Joined")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = "2024-01-01T00:00:00.0000000+00:00",
                            Email = "charles@clovf.com",
                            Joined = "2018-03-07",
                            Name = "김철수",
                            PhoneNumber = "01075312468",
                            UpdatedAt = "2024-01-01T00:00:00.0000000+00:00"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = "2024-01-01T00:00:00.0000000+00:00",
                            Email = "matilda@clovf.com",
                            Joined = "2021-04-28",
                            Name = "박영희",
                            PhoneNumber = "01087654321",
                            UpdatedAt = "2024-01-01T00:00:00.0000000+00:00"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = "2024-01-01T00:00:00.0000000+00:00",
                            Email = "kildong.hong@clovf.com",
                            Joined = "2015-08-15",
                            Name = "홍길동",
                            PhoneNumber = "01012345678",
                            UpdatedAt = "2024-01-01T00:00:00.0000000+00:00"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = "2024-01-01T00:00:00.0000000+00:00",
                            Email = "clo@clovf.com",
                            Joined = "2012-01-05",
                            Name = "김클로",
                            PhoneNumber = "0101111-2424",
                            UpdatedAt = "2024-01-01T00:00:00.0000000+00:00"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = "2024-01-01T00:00:00.0000000+00:00",
                            Email = "md@clovf.com",
                            Joined = "2013-07-01",
                            Name = "박마블",
                            PhoneNumber = "0103535-7979",
                            UpdatedAt = "2024-01-01T00:00:00.0000000+00:00"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = "2024-01-01T00:00:00.0000000+00:00",
                            Email = "connect@clovf.com",
                            Joined = "2019-12-05",
                            Name = "홍커넥",
                            PhoneNumber = "0108531-7942",
                            UpdatedAt = "2024-01-01T00:00:00.0000000+00:00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
